# Generated by Django 4.2.1 on 2023-05-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
