# Generated by Django 4.2.1 on 2023-06-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='label_name',
        ),
    ]
