# Generated by Django 4.2.1 on 2023-06-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_name_address_label_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='raw_response',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paid_at',
        ),
    ]
