# Generated by Django 4.2.1 on 2023-06-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Indonesia', max_length=50),
        ),
    ]
