# Generated by Django 4.2.1 on 2023-06-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_variation_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
