# Generated by Django 4.2.1 on 2023-06-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_transaction_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
