# Generated by Django 4.2.1 on 2023-06-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_transaction_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='success',
        ),
    ]
