# Generated by Django 4.2.1 on 2023-06-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shop', '0018_remove_payment_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
