# Generated by Django 4.2.1 on 2023-06-04 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_transaction_shipping_address_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='none/none.jpg', null=True, upload_to='item_images')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.itemimage'),
        ),
    ]
