# Generated by Django 4.2.1 on 2023-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_rename_itemimage_additionalitemimage_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='none/no_image_available.png', null=True, upload_to='item_images'),
        ),
    ]
